name: wrap
description: Chain style programming and support Flutter without material.
version: 0.0.0
environment: {sdk: ^3.5.2, flutter: ">=3.24.2"}

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false
