name: tools
description: Infrastructure for Dart/Flutter development.
publish_to: none # Just avoid publish monorepo root manager.
version: 0.0.0
environment: {sdk: ^3.5.2}

dev_dependencies:
  strict_lints: ^0.0.0
