name: strict_lints
description: Strict linter options and its parser for Dart's official docs.
version: 0.3.0
environment: {sdk: ^3.5.2}

repository: https://github.com/digso/tools/tree/main/strict_lints

dependencies:
  flutter_lints: ^4.0.0
  html: ^0.15.4
  http: ^1.2.2
  path: ^1.9.0
  yaml_edit: ^2.2.1

dev_dependencies:
  test: ^1.25.8
